auto: true
baseurl: /notes/

pygments: true
markdown: rdiscount
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

nav:
  - text: Top
    url: ""
  - text: Setup
    url: setup/
  - text: Loops
    url: loops/
  - text: Types
    url: types/
  - text: Classes
    url: classes/
